plugins {
    id 'nva.doiregistrar.service.java-conventions'
}

dependencies {
    api(nvaCatalog.aws.lambda.core)
    api(nvaCatalog.jackson.annotations)
    api(nvaLibs.apigateway)
    api(nvaLibs.core)
    api(nvaLibs.eventhandlers)
    api(project(":assign-doi-datacite"))
    api(project(":doi-commons"))
    implementation(libs.jakarta.bind.api)
    implementation(nvaCatalog.log4j.core)
    implementation(nvaCatalog.slf4j.api)
    implementation(nvaCatalog.zalando)
    implementation(nvaLibs.doi)
    implementation(project(":datacite-jaxb"))
    runtimeOnly(libs.jaxb.runtime)
    testImplementation(nvaCatalog.hamcrest)
    testImplementation(nvaCatalog.httpcore5)
    testImplementation(nvaCatalog.jackson.core)
    testImplementation(nvaCatalog.jackson.databind)
    testImplementation(nvaCatalog.junit.jupiter.api)
    testImplementation(nvaCatalog.mockito.core)
    testImplementation(nvaCatalog.wiremock.core)
    testImplementation(nvaCatalog.wiremock.junit5)
    testImplementation(nvaLibs.identifiers)
    testImplementation(nvaLibs.json)
    testImplementation(nvaLibs.logutils)
    testImplementation(nvaLibs.testutils)
    testImplementation(project(':test-utils'))
}

test{
    environment "ALLOWED_ORIGIN", "*"
    environment "API_HOST", "localhost"
    environment "COGNITO_AUTHORIZER_URLS", "http://localhost:3000"
}