plugins {
    id 'nva.java-conventions'
}

group = 'com.github.bibsysdev'

nva {
    errorprone {
        allErrorsAsWarnings = false
    }
    generatedCode = ['org/datacide/schema/**']
    java {
        languageVersion = 21
    }
    pmd {
        rulesetFile = rootProject.file('config/pmd/ruleset.xml')
    }
    spotless {
        enabled = false // FIXME
    }
}


dependencies {
    testImplementation nvaCatalog.junit.jupiter.engine
    testImplementation nvaCatalog.junit.jupiter.params
    testImplementation nvaCatalog.hamcrest
    testImplementation nvaCatalog.mockito.core
    testImplementation nvaLibs.testutils
}
