plugins{
    id 'nva.root-module-conventions'
}

nva {
    dependencyAnalysis {
        enforced = false // FIXME
    }
    generatedCode = ['org/datacide/schema/**']
    jacoco {
        minMethodCoverage = 1.000
        minClassCoverage = 1.000
    }
    spotless {
        enabled = false // FIXME
    }
}
