plugins {
    id 'java'
    id 'pmd'
    id 'jacoco-report-aggregation'
//    id 'test-report-aggregation'
}


group = 'com.github.bibsysdev'

dependencies {
    testImplementation nvaCatalog.junit.jupiter.engine
    testImplementation nvaCatalog.junit.jupiter.params
    testImplementation nvaCatalog.hamcrest
    testImplementation nvaCatalog.mockito.core
    testImplementation nvaLibs.testutils
}

tasks.named('test') {
    useJUnitPlatform {
        excludeTags("online")
    }
    failFast = true
    testLogging {
        events 'skipped', 'passed', 'failed'
    }
}

pmd {
    toolVersion = '6.55.0'
    ruleSetConfig = rootProject.resources.text.fromFile('config/pmd/ruleset.xml')
    ruleSets = []
    ignoreFailures = false
}

check.dependsOn jacocoTestCoverageVerification
jacocoTestCoverageVerification.dependsOn(jacocoTestReport)

jacocoTestCoverageVerification {

    violationRules {
        rule {
            limit {
                counter = 'METHOD'
                value = 'COVEREDRATIO'
                minimum = 1.000
            }
        }

        rule {
            limit {
                counter = 'CLASS'
                value = 'COVEREDRATIO'
                minimum = 1.000
            }
        }
    }
}