AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
  Api:
    Cors:
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowMethods: "'OPTIONS, POST'"
      AllowOrigin: "'*'"


Parameters:
  CognitoAuthorizerArn:
    Type: String
    Description: Reference to Cognito UserPool for the stage
  CustomDomain:
    Type: String
    Description: Custom API to connect this lambda to
  CustomDomainBasePath:
    Type: String
    Description: Base path mapping in CustomDomain
  DataciteMdsConfigs:
    Type: String
    Description: Institution configs for Datacite MDS API
    Default: '{{resolve:secretsmanager:dataciteMdsConfigs:SecretString}}'

Resources:

  NvaDataciteMdsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !Ref CognitoAuthorizerArn
      EndpointConfiguration: Regional
      DefinitionBody:
        openapi: 3.0.0
        info:
          title: NVA Datacite MDS
          version: '1.0'
        paths:
          /:
            post:
              summary:  Todo
              parameters:
                - in: query
                  name: url
                  required: true
                  type: string
                  description: Landing page url
                - in: query
                  name: dataciteXml
                  required: true
                  type: string
                  description: Datacite XML
                - in: query
                  name: institutionId
                  required: true
                  type: string
                  description: Institution id
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${NvaDataciteMdsFunction.Arn}/invocations
                responses: {}
                httpMethod: POST
                type: AWS_PROXY
              responses:
                '201':
                  description: Created.
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/createDoiResponseBody'
                '400':
                  description: Bad request.
                  content:
                    application/json:
                      schema:
                        title: 400 Bad Request
                        type: object
                        properties:
                          error:
                            type: string
                            description: error message
                '402':
                  description: Payment required.
                  content:
                    application/json:
                      schema:
                        title: 400 Payment Required
                        type: object
                        properties:
                          error:
                            type: string
                            description: error message
                '500':
                  description: Internal server error.
                  content:
                    application/json:
                      schema:
                        title: 500 Bad Internal Server Error
                        type: object
                        properties:
                          error:
                            type: string
                            description: error message

        components:
          securitySchemes:
            CognitoUserPool:
              type: apiKey
              name: Authorization
              in: header
              x-amazon-apigateway-authtype: cognito_user_pools
              x-amazon-apigateway-authorizer:
                type: cognito_user_pools
                providerARNs:
                  - !Ref CognitoAuthorizerArn
          schemas:
            createDoiResponseBody:
              title: Doi created
              type: string
              description: The created doi

  NvaDataciteMdsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Environment:
        Variables:
          DATACITE_MDS_CONFIGS: !Ref DataciteMdsConfigs
          ALLOWED_ORIGIN:  '*'
      Handler: no.unit.nva.datacite.DataciteMdsCreateDoiHandler::handleRequest
      Runtime: java8
      MemorySize: 512
      Events:
        NvaDataciteMdsEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref NvaDataciteMdsApi
            Path: /
            Method: post

  NvaDataciteMdsBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref CustomDomainBasePath
      DomainName: !Ref CustomDomain
      RestApiId: !Ref NvaDataciteMdsApi
      Stage: !Ref NvaDataciteMdsApi.Stage
