AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

Metadata:
  AWS::ServerlessRepo::Application:
    Name: NvaDoiRegistrarClient
    Description: Client for communicating with DOI Registrars (DataCite)
    Author: Unit
    SemanticVersion: 1.0.0
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE

Globals:
  Function:
    Timeout: 20

Parameters:
  DataCiteMdsConfigs:
    Type: String
    Description: Institution configs for DataCite MDS API
    Default: '{{resolve:secretsmanager:dataCiteCustomerSecrets:SecretString}}'
  DataCiteHost:
    Type: String
    Default: mds.test.datacite.org
  DataCitePort:
    Type: String
    Default: 443
  EventBusName:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: nvaEventBusName
  EventBusArn:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: nvaEventBusArn

Resources:
  DataCiteDraftDoiHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: datacite-draft-doi-handler
      Handler: no.unit.nva.datacite.handlers.FindableDoiEventHandler::handleRequest
      Runtime: java11
      MemorySize: 1408
      Environment:
        Variables:
          EVENT_BUS: !Ref EventBusName
          AWC_ACCOUNT_ID: !Ref AWS::AccountId
          DATACITE_CONFIG: !Ref DataCiteMdsConfigs
          DATACITE_HOST: !Ref DataCiteHost
          DATACITE_PORT: !Ref DataCitePort
      Events:
        EventBridgeEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref EventBusName
            Pattern:
              detail-type: [ "Lambda Function Invocation Result - Success" ]
              detail:
                responsePayload:
                  type:
                    - doi.publication
                  item:
                    doiRequest:
                      status:
                        - APPROVED
                    doi:
                      - exists: false
                    sameModifiedDateForDoiRequest:
                      - true
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: SQS
            Destination: !Ref EventBusArn
          OnFailure:
            Type: SQS
            Destination: !GetAtt DataCiteDraftDoiHandlerDLQ.Arn
  DataCiteDraftDoiHandlerDLQ:
    Type: "AWS::SQS::Queue"

  DataCiteFindableDoiHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: datacite-draft-doi-handler
      Handler: no.unit.nva.datacite.handlers.FindableDoiEventHandler::handleRequest
      Runtime: java11
      MemorySize: 1408
      Environment:
        Variables:
          EVENT_BUS: !Ref EventBusName
          AWC_ACCOUNT_ID: !Ref AWS::AccountId
          DATACITE_CONFIG: !Ref DataCiteMdsConfigs
          DATACITE_HOST: !Ref DataCiteHost
          DATACITE_PORT: !Ref DataCitePort
      Events:
        EventBridgeEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref EventBusName
            Pattern:
              detail-type: [ "Lambda Function Invocation Result - Success" ]
              detail:
                responsePayload:
                  type:
                    - doi.publication
                  item:
                    doiRequest:
                      status:
                        - APPROVED
                    doi:
                      - exists: true
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: SQS
            Destination: !Ref EventBusArn
          OnFailure:
            Type: SQS
            Destination: !GetAtt DataCiteFindableDoiHandlerDLQ.Arn
  DataCiteFindableDoiHandlerDLQ:
    Type: "AWS::SQS::Queue"

