AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

Parameters:
  DataCiteMdsHost:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: dataCiteMdsHost
  DataCiteRestHost:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: dataCiteRestHost
  EventBusName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/NVA/Events/EventsBusName'
  EventBusArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/NVA/Events/EventsBusArn'
  ApiDomain:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/NVA/ApiDomain'
  CustomerSecretsSecretName:
    Type: String
    Default: dataCiteCustomerSecrets
  CustomerSecretsSecretKey:
    Type: String
    Default: dataCiteCustomerSecrets
  DoiHost:
    Type: String


Globals:
  Function:
    Timeout: 60
    Environment:
      Variables:
        API_HOST: !Ref ApiDomain


Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LambdaDefaults
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
        - PolicyName: InvokeLambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                #Allow all resources to avoid circular dependencies.
                Resource: '*'
        - PolicyName: SqsEvents
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:DeleteMessage
                Resource:
                  - !GetAtt DataCiteDraftDoiHandlerDLQ.Arn
                  - !GetAtt DataCiteFindableDoiHandlerDLQ.Arn
                  - !GetAtt DeleteDraftDoiHandlerDLQ.Arn
        - PolicyName: EventBridgeEvents
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - events:PutEvents
                  - events:PutRule
                Resource: !Ref EventBusArn
        - PolicyName: ReadSecrets
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetResourcePolicy
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                  - secretsmanager:ListSecretVersionIds
                Resource:
                  Fn::Sub: arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${CustomerSecretsSecretName}*


  DataCiteDraftDoiHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: datacite-draft-doi-handler
      Handler: no.unit.nva.datacite.handlers.DraftDoiHandler::handleRequest
      Runtime: java11
      MemorySize: 1408
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          EVENT_BUS: !Ref EventBusName
          AWC_ACCOUNT_ID: !Ref AWS::AccountId
          CUSTOMER_SECRETS_SECRET_NAME: !Ref CustomerSecretsSecretName
          CUSTOMER_SECRETS_SECRET_KEY: !Ref CustomerSecretsSecretKey
          DATACITE_REST_HOST: !Ref DataCiteRestHost
          DATACITE_MDS_HOST: !Ref DataCiteMdsHost
          DOI_HOST: !Ref DoiHost

      Events:
        EventBridgeEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref EventBusName
            Pattern:
              detail-type: [ "Lambda Function Invocation Result - Success" ]
              detail:
                responsePayload:
                  topic:
                    - PublicationService.Doi.CreationRequest
                    - PublicationService.Doi.UpdateRequest
                  item:
                    doi:
                      - exists: false
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: EventBridge
            Destination: !Ref EventBusArn
          OnFailure:
            Type: SQS
            Destination: !GetAtt DataCiteDraftDoiHandlerDLQ.Arn


  DataCiteFindableDoiHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: datacite-findable-doi-handler
      Handler: no.unit.nva.datacite.handlers.FindableDoiEventHandler::handleRequest
      Runtime: java11
      MemorySize: 1408
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          EVENT_BUS: !Ref EventBusName
          AWC_ACCOUNT_ID: !Ref AWS::AccountId
          CUSTOMER_SECRETS_SECRET_NAME: !Ref CustomerSecretsSecretName
          CUSTOMER_SECRETS_SECRET_KEY: !Ref CustomerSecretsSecretKey
          DATACITE_REST_HOST: !Ref DataCiteRestHost
          DATACITE_MDS_HOST: !Ref DataCiteMdsHost
          DOI_HOST: !Ref DoiHost
      Events:
        EventBridgeEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref EventBusName
            Pattern:
              detail-type: [ "Lambda Function Invocation Result - Success" ]
              detail:
                responsePayload:
                  topic:
                    - PublicationService.Doi.UpdateRequest
                  item:
                    status:
                      - PUBLISHED
                    doi:
                      - exists: true
      EventInvokeConfig:
        DestinationConfig:
          OnFailure:
            Type: SQS
            Destination: !GetAtt DataCiteDraftDoiHandlerDLQ.Arn

  DeleteDraftDoiHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: datacite-delete-draft-doi-handler
      Handler: no.unit.nva.datacite.handlers.DeleteDraftDoiHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          EVENT_BUS: !Ref EventBusName
          AWC_ACCOUNT_ID: !Ref AWS::AccountId
          CUSTOMER_SECRETS_SECRET_NAME: !Ref CustomerSecretsSecretName
          CUSTOMER_SECRETS_SECRET_KEY: !Ref CustomerSecretsSecretKey
          DATACITE_REST_HOST: !Ref DataCiteRestHost
          DATACITE_MDS_HOST: !Ref DataCiteMdsHost
          DOI_HOST: !Ref DoiHost
      Events:
        EventBridgeEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref EventBusName
            Pattern:
              detail:
                responsePayload:
                  topic:
                    - PublicationService.Resource.DraftForDeletion
                  hasDoi:
                    - true
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: EventBridge
            Destination: !Ref EventBusArn
          OnFailure:
            Type: SQS
            Destination: !GetAtt DeleteDraftDoiHandlerDLQ.Arn

  DataCiteFindableDoiHandlerDLQ:
    Type: "AWS::SQS::Queue"

  DataCiteDraftDoiHandlerDLQ:
    Type: "AWS::SQS::Queue"

  DeleteDraftDoiHandlerDLQ:
    Type: "AWS::SQS::Queue"



