AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

Parameters:
  CognitoAuthorizerArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Reference to Cognito UserPool for the stage
    Default: CognitoAuthorizerArn
  CustomDomainBasePath:
    Type: String
    Description: Base path mapping in CustomDomain
    Default: doi-registrar
  DataCiteMdsHost:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: dataCiteMdsHost
  DataCiteRestHost:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: dataCiteRestHost
  EventBusName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/NVA/Events/EventsBusName'
  EventBusArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/NVA/Events/EventsBusArn'
  EventsBucketsName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/NVA/Events/EventsBucketName'
  ApiDomain:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/NVA/ApiDomain'
  CustomerSecretsSecretName:
    Type: String
    Default: dataCiteCustomerSecrets
  CustomerSecretsSecretKey:
    Type: String
    Default: dataCiteCustomerSecrets
  DoiHost:
    Type: String
  Suffix:
    Type: String
    Default: ''
    Description: Suffix used for naming resources for feature branches to avoid conflicts.
  SlackSnsArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/NVA/Monitoring/SlackSnsArn'
  AllowedOrigins:
    Type: String
    Description: comma separated list of external clients that are allowed to contact the HTTP APIs, "*" indicates that all origins are allowed
    Default: '*'

Conditions:
  WithSuffix: !Not [ !Equals [ !Ref Suffix, '' ] ]

Globals:
  Function:
    Timeout: 60
    Runtime: java21
    MemorySize: 1408
    Environment:
      Variables:
        API_HOST: !Ref ApiDomain


Resources:

  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 90

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LambdaDefaults
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
        - PolicyName: InvokeLambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                #Allow all resources to avoid circular dependencies.
                Resource: '*'
        - PolicyName: SqsEvents
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:DeleteMessage
                Resource:
                  - !GetAtt DataCiteDraftDoiHandlerDLQ.Arn
                  - !GetAtt DataCiteFindableDoiHandlerDLQ.Arn
                  - !GetAtt DataCiteDeleteDraftDoiHandlerDLQ.Arn
                  - !GetAtt ResourceDraftedForDeletionEventHandlerDLQ.Arn
        - PolicyName: EventBridgeEvents
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - events:PutEvents
                  - events:PutRule
                Resource: !Ref EventBusArn
        - PolicyName: ReadSecrets
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetResourcePolicy
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                  - secretsmanager:ListSecretVersionIds
                Resource:
                  Fn::Sub: arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${CustomerSecretsSecretName}*

  DataCiteUpdateDoiHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: datacite-update-doi-handler
      Handler: no.unit.nva.datacite.handlers.UpdateDoiEventHandler::handleRequest
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          EVENT_BUS: !Ref EventBusName
          AWC_ACCOUNT_ID: !Ref AWS::AccountId
          CUSTOMER_SECRETS_SECRET_NAME: !Ref CustomerSecretsSecretName
          CUSTOMER_SECRETS_SECRET_KEY: !Ref CustomerSecretsSecretKey
          DATACITE_REST_HOST: !Ref DataCiteRestHost
          DATACITE_MDS_HOST: !Ref DataCiteMdsHost
          DOI_HOST: !Ref DoiHost
      Events:
        EventBridgeEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref EventBusName
            Pattern:
              detail-type: [ "Lambda Function Invocation Result - Success" ]
              detail:
                responsePayload:
                  topic:
                    - PublicationService.Doi.UpdateRequest
                  doi:
                    - exists: true
      EventInvokeConfig:
        DestinationConfig:
          OnFailure:
            Type: SQS
            Destination: !GetAtt DataCiteDraftDoiHandlerDLQ.Arn

  ResourceDraftedForDeletion:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: datacite-delete-draft-doi-handler
      Handler: no.unit.nva.datacite.handlers.resource.ResourceDraftedForDeletionEventHandler::handleRequest
      MemorySize: 512
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          EVENT_BUS: !Ref EventBusName
          AWC_ACCOUNT_ID: !Ref AWS::AccountId
          CUSTOMER_SECRETS_SECRET_NAME: !Ref CustomerSecretsSecretName
          CUSTOMER_SECRETS_SECRET_KEY: !Ref CustomerSecretsSecretKey
          DATACITE_REST_HOST: !Ref DataCiteRestHost
          DATACITE_MDS_HOST: !Ref DataCiteMdsHost
          DOI_HOST: !Ref DoiHost
      Events:
        EventBridgeEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref EventBusName
            Pattern:
              detail-type: [ "Lambda Function Invocation Result - Success" ]
              detail:
                responsePayload:
                  topic:
                    - PublicationService.Resource.DraftForDeletion
                  hasDoi:
                    - true

  DataCiteReserveDraftDoiHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: datacite-draft-doi-handler
      Handler: no.unit.nva.datacite.handlers.ReserveDraftDoiHandler::handleRequest
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          AWC_ACCOUNT_ID: !Ref AWS::AccountId
          CUSTOMER_SECRETS_SECRET_NAME: !Ref CustomerSecretsSecretName
          CUSTOMER_SECRETS_SECRET_KEY: !Ref CustomerSecretsSecretKey
          DATACITE_REST_HOST: !Ref DataCiteRestHost
          DATACITE_MDS_HOST: !Ref DataCiteMdsHost
          DOI_HOST: !Ref DoiHost
          ALLOWED_ORIGIN: !Ref AllowedOrigins
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /draft
            Method: post
            RestApiId: !Ref NvaDoiRegistrarClientApi

  DataCiteFindableDoiHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: datacite-update-doi-handler
      Handler: no.unit.nva.datacite.handlers.FindableDoiHandler::handleRequest
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          EVENT_BUS: !Ref EventBusName
          AWC_ACCOUNT_ID: !Ref AWS::AccountId
          CUSTOMER_SECRETS_SECRET_NAME: !Ref CustomerSecretsSecretName
          CUSTOMER_SECRETS_SECRET_KEY: !Ref CustomerSecretsSecretKey
          DATACITE_REST_HOST: !Ref DataCiteRestHost
          DATACITE_MDS_HOST: !Ref DataCiteMdsHost
          DOI_HOST: !Ref DoiHost
          ALLOWED_ORIGIN: !Ref AllowedOrigins
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /findable
            Method: post
            RestApiId: !Ref NvaDoiRegistrarClientApi

  DataCiteDeleteDraftDoiHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: datacite-delete-draft-doi-handler
      Handler: no.unit.nva.datacite.handlers.doi.DeleteDraftDoiHandler::handleRequest
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          EVENT_BUS: !Ref EventBusName
          AWC_ACCOUNT_ID: !Ref AWS::AccountId
          CUSTOMER_SECRETS_SECRET_NAME: !Ref CustomerSecretsSecretName
          CUSTOMER_SECRETS_SECRET_KEY: !Ref CustomerSecretsSecretKey
          DATACITE_REST_HOST: !Ref DataCiteRestHost
          DATACITE_MDS_HOST: !Ref DataCiteMdsHost
          DOI_HOST: !Ref DoiHost
          ALLOWED_ORIGIN: !Ref AllowedOrigins
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /draft/{doiPrefix}/{doiSuffix}
            Method: delete
            RestApiId: !Ref NvaDoiRegistrarClientApi


  NvaDoiRegistrarClientApi:
    Type: AWS::Serverless::Api
    Properties:
      AccessLogSetting:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: '{ "apiId": "$context.apiId", "requestId": "$context.requestId", "requestTime": "$context.requestTime", "requestTimeEpoch": "$context.requestTimeEpoch", "httpMethod": "$context.httpMethod", "path": "$context.path", "status": "$context.status",  "error.message": "$context.error.message" }'
      StageName: Prod
      EndpointConfiguration: REGIONAL
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: ./docs/openapi.yaml

  #===========================BasePathMappings========================================================#

  NvaDoiRegistrarClientBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !If
        - WithSuffix
        - !Sub ${CustomDomainBasePath}-${Suffix}
        - !Sub ${CustomDomainBasePath}
      DomainName: !Ref ApiDomain
      RestApiId: !Ref NvaDoiRegistrarClientApi
      Stage: !Ref NvaDoiRegistrarClientApi.Stage

  DataCiteFindableDoiHandlerDLQ:
    Type: "AWS::SQS::Queue"

  DataCiteDraftDoiHandlerDLQ:
    Type: "AWS::SQS::Queue"

  DataCiteDeleteDraftDoiHandlerDLQ:
    Type: "AWS::SQS::Queue"

  ResourceDraftedForDeletionEventHandlerDLQ:
    Type: "AWS::SQS::Queue"

  #============================= Alarms =========================================================

  DataCiteFindableDoiHandlerDLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: Doi-registrar creating findable doi failed
      AlarmDescription: If this alarm is triggered, then check sqs messages on DataCiteFindableDoiHandlerDLQ. Creating findable DOI has failed.
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Statistic: Sum
      Dimensions:
        - Name: QueueName
          Value: !GetAtt DataCiteFindableDoiHandlerDLQ.QueueName
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref SlackSnsArn

  DataCiteDraftDoiHandlerDLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: Doi-registrar creating draft doi failed
      AlarmDescription: If this alarm is triggered, then check sqs messages on DataCiteDraftDoiHandlerDLQ. Creating draft DOI has failed.
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Statistic: Sum
      Dimensions:
        - Name: QueueName
          Value: !GetAtt DataCiteDraftDoiHandlerDLQ.QueueName
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref SlackSnsArn

  DataCiteDeleteDraftDoiHandlerDLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: Doi-registrar deleting draft doi failed
      AlarmDescription: If this alarm is triggered, then check sqs messages on DataCiteDeleteDraftDoiHandlerDLQ. Deleting draft DOI has failed.
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Statistic: Sum
      Dimensions:
        - Name: QueueName
          Value: !GetAtt DataCiteDeleteDraftDoiHandlerDLQ.QueueName
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref SlackSnsArn

  ResourceDraftedForDeletionEventHandlerDLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: Doi-registrar delete draft resource event error
      AlarmDescription: If this alarm is triggered, then check sqs messages on ResourceDraftedForDeletionEventHandlerDLQ.
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Statistic: Sum
      Dimensions:
        - Name: QueueName
          Value: !GetAtt ResourceDraftedForDeletionEventHandlerDLQ.QueueName
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref SlackSnsArn

  #============================ Global events ======================================================

  ExternalUpdatesQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 900
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ExternalUpdatesDLQ.Arn
        maxReceiveCount: 5

  ExternalUpdatesDLQ:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600 #14 days

  ExternalUpdatesDLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: ExternalUpdatesDLQ Alarm in nva-doi-registrar-client
      AlarmDescription: If this alarm is triggered, then check sqs messages on ExternalUpdatesDLQ
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Statistic: Sum
      Dimensions:
        - Name: QueueName
          Value: !GetAtt ExternalUpdatesDLQ.QueueName
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref SlackSnsArn

  ExternalUpdateEventsRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: !Ref EventBusName
      Description: "Event rule to listen to external updates."
      State: ENABLED
      EventPattern:
        detail:
          responsePayload:
            topic:
              - "PublicationService.Resource.Deleted"
      Targets:
        - Arn: !GetAtt ExternalUpdatesQueue.Arn
          Id: ExternalUpdatesQueueTarget
          DeadLetterConfig:
            Arn: !GetAtt ExternalUpdatesDLQ.Arn

  ExternalUpdatesQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref ExternalUpdatesQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: "events.amazonaws.com"
            Action: 'sqs:SendMessage'
            Resource: !GetAtt ExternalUpdatesQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !GetAtt ExternalUpdateEventsRule.Arn

  ConsumeMessagesFromExternalEventsQueueManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: 'Managed IAM policy to consume messages from external events queue'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Resource: !GetAtt ExternalUpdatesQueue.Arn

  ReadDataCiteCredentialsManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: 'Managed IAM policy to read secrets required to authenticate to datacite on behalf of customers'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              Fn::Sub: arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${CustomerSecretsSecretName}*

  ReadEventBucketManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: 'Managed IAM policy to consume messages from external events queue'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource: !Sub "arn:aws:s3:::${EventsBucketsName}/*"

  ExternalUpdatesEventHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: datacite-delete-draft-doi-handler
      Handler: no.unit.nva.datacite.handlers.resource.ExternalUpdatesEventHandler::handleRequest
      Timeout: 900
      Policies:
        - !Ref ReadDataCiteCredentialsManagedPolicy
        - !Ref ConsumeMessagesFromExternalEventsQueueManagedPolicy
        - !Ref ReadEventBucketManagedPolicy
      Environment:
        Variables:
          EVENTS_BUCKET_NAME: !Ref EventsBucketsName
      Events:
        ExternalUpdatesQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ExternalUpdatesQueue.Arn
