plugins {
    id 'nva.doiregistrar.service.java-conventions'
}

dependencies {
    api nvaLibs.eventhandlers
    api project (":doi-commons")
    implementation nvaCatalog.jackson.databind
    implementation nvaCatalog.wiremock.core
    implementation nvaLibs.core
    implementation nvaLibs.json
}

test{
    environment "ALLOWED_ORIGIN", "*"
    environment "API_HOST", "api.localhost.nva.unit.no"
}
