plugins {
    id 'nva.doiregistrar.service.java-conventions'
}

dependencies {
    api(nvaCatalog.aws.lambda.core)
    api(nvaCatalog.jackson.annotations)
    api(nvaLibs.apigateway)
    api(nvaLibs.core)
    api(project(":assign-doi-datacite"))
    implementation(nvaCatalog.log4j.core)
    implementation(nvaCatalog.slf4j.api)
    implementation(nvaLibs.doi)
    testImplementation(nvaCatalog.hamcrest)
    testImplementation(nvaCatalog.httpcore5)
    testImplementation(nvaCatalog.jackson.core)
    testImplementation(nvaCatalog.jackson.databind)
    testImplementation(nvaCatalog.junit.jupiter.api)
    testImplementation(nvaCatalog.mockito.core)
    testImplementation(nvaCatalog.wiremock.junit5)
    testImplementation(nvaCatalog.zalando)
    testImplementation(nvaLibs.json)
    testImplementation(nvaLibs.testutils)
}

test {
    environment "ALLOWED_ORIGIN", "*"
    environment "DATACITE_REST_HOST", "someHost"
}
