dependencies {
    implementation nvaLibs.core
    implementation nvaLibs.json
    implementation nvaLibs.identifiers

    implementation nvaCatalog.jackson.core
    implementation nvaCatalog.jackson.databind
    implementation nvaCatalog.jackson.annotations
    implementation nvaCatalog.jackson.datatype.jdk8
    implementation nvaCatalog.jackson.datatype.jsr310
    implementation nvaCatalog.jackson.datatype.problem
}
